blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/srikanth-karthi/mcp-portfolio/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/srikanth-karthi/mcp-portfolio/security/advisories/new
    about: Report security vulnerabilities privately
